### ISSUE TITLE
Update sksurgeryutils.

### ISSUE THREAD

**Issue by thompson318** [SciKit-Surgery/scikit-surgerytutorial01#30]

**Comment by mxochicale** [comment]
What do you mean here? 
* make use of `scikit-surgeryvtk`to replace`from sksurgeryutils.common_overlay_apps import OverlayBaseWidget`, 
* use the latest version of sksurgeryutils?, or
* anything else

Thanks

**Comment by thompson318** [comment]
It was to update the version of sksurgeryutils. It looks like you've done this at 396741744, thanks. I'll close this.
